const list = [
    {
      id: 1,
      title: "Bread",
      price: 1.20,
      img: "https://www.pngplay.com/wp-content/uploads/1/Bread-Sandwich-PNG-Clipart-Background.png",
      amount: 1,
    },
    {
      id: 3,
      title: "Pasta",
      price: 0.99,
      img: "https://www.pngplay.com/wp-content/uploads/4/Pasta-Transparent-Image.png",
      amount: 1,
    },
    {
      id: 4,
      title: "Pizza",
      price: 2.80,
      img: "https://www.pngplay.com/wp-content/uploads/2/Top-View-Pizza-PNG-HD-Quality.png",
      amount: 1,
    },
    {
      id: 5,
      title: "Milk",
      price: 1.49,
      img: "https://www.pngplay.com/wp-content/uploads/4/Milk-Background-PNG-Image.png",
      amount: 1,
    },
    {
      id: 6,
      title: "Eggs",
      price: 1.35,
      img: "https://www.pngplay.com/wp-content/uploads/2/Eggs-Download-Free-PNG.png",
      amount: 1,
    },
    {
      id: 7,
      title: "Cheese",
      price: 2.93,
      img: "https://www.pngplay.com/wp-content/uploads/4/Cheese-Download-Free-PNG.png",
      amount: 1,
    },
    {
      id: 8,
      title: "Yogurt",
      price: 2.89,
      img: "https://www.pngplay.com/wp-content/uploads/4/Yogurt-Transparent-File.png",
      amount: 1,
    },
    {
      id: 10,
      title: "Beef",
      price: 5.49,
      img: "https://www.pngplay.com/wp-content/uploads/4/Beef-PNG-Photos.png",
      amount: 1,
    },
    {
      id: 11,
      title: "Tofu",
      price: 1.20,
      img: "https://www.pngplay.com/wp-content/uploads/8/Tofu-Burger-Download-Free-PNG.png",
      amount: 1,
    },
    {
      id: 12,
      title: "Shrimp",
      price: 4.59,
      img: "https://www.pngplay.com/wp-content/uploads/1/Shrimp-PNG-Images-HD.png",
      amount: 1,
    },
    {
      id: 13,
      title: "Potatoes",
      price: 0.79,
      img: "https://www.pngplay.com/wp-content/uploads/4/Potato-Free-PNG.png",
      amount: 1,
    },
    {
        id: 15,
        title: "Tomatoes",
        price: 0.29,
        img: "https://www.pngplay.com/wp-content/uploads/1/Tomato-PNG-Free-Commercial-Use-Image.png",
        amount: 1,
    },
    {
        id: 16,
        title: "Carrots",
        price: 0.29,
        img: "https://www.pngplay.com/wp-content/uploads/15/Carrots-Free-PNG.png",
        amount: 1,
    },
    {
        id: 17,
        title: "Apple",
        price: 0.19,
        img: "https://www.pngplay.com/wp-content/uploads/12/Apples-Clipart-PNG-Background.png",
        amount: 1,
    },
    {
        id: 18,
        title: "Orange",
        price: 0.22,
        img: "https://www.pngplay.com/wp-content/uploads/15/Oranges-Transparent-PNG.png",
        amount: 1,
    },
    {
        id: 19,
        title: "Peach",
        price: 0.39,
        img: "https://www.pngplay.com/wp-content/uploads/6/Peach-Slice-Transparent-PNG.png",
        amount: 1,
    },
    {
        id: 20,
        title: "Limes",
        price: 0.42,
        img: "https://www.pngplay.com/wp-content/uploads/6/Limes-PNG.png",
        amount: 1,
    },
    {
        id: 21,
        title: "Water",
        price: 0.12,
        img: "https://www.pngplay.com/wp-content/uploads/4/Water-Bottle-No-Background.png",
        amount: 1,
    },
    {
        id: 22,
        title: "Soda",
        price: 0.89,
        img: "https://www.pngplay.com/wp-content/uploads/9/Soda-PNG-Free-File-Download.png",
        amount: 1,
    },
    {
        id: 24,
        title: "Beer",
        price: 1.19,
        img: "https://www.pngplay.com/wp-content/uploads/14/Beer-Can-Stella-Artois-PNG-Clipart-Background-1.png",
        amount: 1,
    },
    {
        id: 25,
        title: "Olive Oil",
        price: 4.49,
        img: "https://www.pngplay.com/wp-content/uploads/2/Olive-Oil-Free-PNG.png",
        amount: 1,
    },
    {
        id: 26,
        title: "Salt",
        price: 0.19,
        img: "https://www.pngplay.com/wp-content/uploads/2/Salt-Transparent-Background.png",
        amount: 1,
    },
    {
        id: 27,
        title: "Pepper",
        price: 0.29,
        img: "https://www.pngplay.com/wp-content/uploads/2/Black-Pepper-Transparent-File.png",
        amount: 1,
    },
    {
        id: 17,
        title: "Honey",
        price: 2.39,
        img: "https://www.pngplay.com/wp-content/uploads/2/Honey-Download-Free-PNG.png",
        amount: 1,
    },

];
  
export default list;
